"""add movie embeddings

Revision ID: 03270bb8bca6
Revises: 548f96ebc4a3
Create Date: 2026-08-28 19:52:27.981075

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03270bb8bca6'
down_revision: Union[str, Sequence[str], None] = '548f96ebc4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('embedding', VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'embedding')
    # ### end Alembic commands ###
