"""use tmdb ids for unique terms

Revision ID: 548f96ebc4a3
Revises: aa9d08f6a199
Create Date: 2026-08-28 12:49:50.363571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548f96ebc4a3'
down_revision: Union[str, Sequence[str], None] = 'aa9d08f6a199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('genres_name_key'), 'genres', type_='unique')
    op.drop_constraint(op.f('keywords_name_key'), 'keywords', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('keywords_name_key'), 'keywords', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('genres_name_key'), 'genres', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
