"""normalize movie metadata

Revision ID: aa9d08f6a199
Revises: eddedaaba21e
Create Date: 2026-08-27 17:03:54.974914

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa9d08f6a199"
down_revision: Union[str, Sequence[str], None] = "eddedaaba21e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_genres_tmdb_id"), "genres", ["tmdb_id"], unique=True)
    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_keywords_tmdb_id"), "keywords", ["tmdb_id"], unique=True)
    op.create_table(
        "movie_genres",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("movie_id", "genre_id"),
    )
    op.create_table(
        "movie_keywords",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["keyword_id"], ["keywords.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("movie_id", "keyword_id"),
    )
    op.add_column("movies", sa.Column("tmdb_id", sa.Integer(), nullable=False))
    op.add_column("movies", sa.Column("original_title", sa.String(length=255), nullable=True))
    op.add_column("movies", sa.Column("tagline", sa.Text(), nullable=True))
    op.add_column("movies", sa.Column("vote_count", sa.Integer(), nullable=True))
    op.add_column("movies", sa.Column("popularity", sa.Float(), nullable=True))
    op.add_column("movies", sa.Column("certification_country", sa.String(length=2), nullable=True))
    op.add_column("movies", sa.Column("poster_path", sa.String(length=255), nullable=True))
    op.add_column("movies", sa.Column("searchable_description", sa.Text(), nullable=True))
    op.add_column(
        "movies",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_movies_tmdb_id"), "movies", ["tmdb_id"], unique=True)
    op.create_check_constraint(
        "ck_movies_popularity_nonnegative", "movies", "popularity IS NULL OR popularity >= 0"
    )
    op.create_check_constraint(
        "ck_movies_vote_count_nonnegative", "movies", "vote_count IS NULL OR vote_count >= 0"
    )
    op.drop_column("movies", "genres")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column(
            "genres", postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint("ck_movies_vote_count_nonnegative", "movies", type_="check")
    op.drop_constraint("ck_movies_popularity_nonnegative", "movies", type_="check")
    op.drop_index(op.f("ix_movies_tmdb_id"), table_name="movies")
    op.drop_column("movies", "updated_at")
    op.drop_column("movies", "searchable_description")
    op.drop_column("movies", "poster_path")
    op.drop_column("movies", "certification_country")
    op.drop_column("movies", "popularity")
    op.drop_column("movies", "vote_count")
    op.drop_column("movies", "tagline")
    op.drop_column("movies", "original_title")
    op.drop_column("movies", "tmdb_id")
    op.drop_table("movie_keywords")
    op.drop_table("movie_genres")
    op.drop_index(op.f("ix_keywords_tmdb_id"), table_name="keywords")
    op.drop_table("keywords")
    op.drop_index(op.f("ix_genres_tmdb_id"), table_name="genres")
    op.drop_table("genres")
    # ### end Alembic commands ###
