"""create movies table

Revision ID: eddedaaba21e
Revises: c8a90d02410b
Create Date: 2026-08-27 14:32:21.750781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eddedaaba21e'
down_revision: Union[str, Sequence[str], None] = 'c8a90d02410b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('age_rating', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 10)', name='ck_movies_rating_range'),
    sa.CheckConstraint('runtime_minutes IS NULL OR runtime_minutes > 0', name='ck_movies_runtime_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_original_language'), 'movies', ['original_language'], unique=False)
    op.create_index(op.f('ix_movies_release_year'), 'movies', ['release_year'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_release_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_original_language'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
